### ISSUE TITLE
Finding source documents for project (sample project issue with task list)

### ISSUE THREAD

**Issue by ebeshero** [newtfire/digitProjectDesign-Hub#25]
- [x] Search for historic recipes with "nineteenth century recipes" and "eighteenth-century recipes". @fammysillar 

- [ ] Post links to good resources on this issue. @fammysillar

**Comment by ebeshero** [comment]
- [ ] Check your GitHub notifications: Are you receiving email when you are mentioned?
